postgresql:
  image: sameersbn/postgresql:9.4-11
  environment:
    - DB_USER=owncloud
    - DB_PASS=password
    - DB_NAME=owncloud_db
  volumes:
    - /srv/docker/owncloud/postgresql:/var/lib/postgresql

owncloud:
  image: sameersbn/owncloud:latest
  command: app:owncloud
  environment:
    - DEBUG=false
    - OWNCLOUD_FQDN=cloud.example.com
    - OWNCLOUD_UPLOAD_MAX_FILESIZE=4G
    - OWNCLOUD_MAX_FILE_UPLOADS=20
  links:
    - postgresql:postgresql
  volumes:
    - /srv/docker/owncloud/owncloud:/var/lib/owncloud

nginx:
  image: sameersbn/owncloud:latest
  command: app:nginx
  links:
    - owncloud:owncloud-php-fpm
  ports:
    - "80:80"
