postgresql:
  image: sameersbn/postgresql:latest
  environment:
    - DB_USER=owncloud
    - DB_PASS=password
    - DB_NAME=owncloud_db
  volumes:
    - /srv/docker/owncloud/postgresql:/var/lib/postgresql

owncloud:
  image: sameersbn/owncloud:latest
  environment:
    - DEBUG=false
    - OWNCLOUD_FQDN=cloud.example.com
    - OWNCLOUD_UPLOAD_MAX_FILESIZE=4G
    - OWNCLOUD_MAX_FILE_UPLOADS=20
  links:
    - postgresql:postgresql
  volumes:
    - /srv/docker/owncloud/owncloud:/var/lib/owncloud
    - /srv/docker/owncloud/nginx/sites-enabled:/etc/nginx/sites-enabled

nginx:
  image: sameersbn/nginx
  links:
    - owncloud:owncloud-php-fpm
  volumes:
    - /srv/docker/owncloud/nginx/sites-enabled:/etc/nginx/sites-enabled
  volumes_from:
    - owncloud
  ports:
    - "80:80"
